#name: Node.js CI
#
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [10.x, 12.x]
#    steps:
#      - uses: actions/checkout@v2
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node-version }}
#      - run: npm ci
#      - run: npm run build --if-present
#      - run: npm test
#        env:
#          CI: true
#      - name: Deploy
#          uses: JamesIves/github-pages-deploy-action@releases/v3
#          with:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#            BRANCH: gh-pages
#            FOLDER: dist


name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm install
          npm run-script build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist